# All containers use the docker network prime-net. 
# Each container is assigned a distinct id 
# and its IP address is derived from base ip (172.20.0.0)+ID+1
networks:
  prime-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
    name: prime-net

# This topology consists of 6 replicas, satisfying NUM_SERVERS=3f+2k+1 (prime/src/def.h)
# where f = 1 for # of tolerated Byzantine replicas and k=1 for # of tolerated benign replicas

# TODO: add more serves to evaluate local scalability
services:

  # Only instance of driver.c is run from replica prime1. Once a baseline throughput is established,
  # running multiple instances of this program would be an interesting follow up stress test evaluation. 
  prime1:
    image: replica-img
    container_name: prime1
    networks:
      prime-net:
        ipv4_address: 172.20.0.2
    command: python3 /root/cs2910/prime/docker/startup.py 1

  prime2:
    image: replica-img
    container_name: prime2
    networks:
      prime-net:
        ipv4_address: 172.20.0.3
    command: python3 /root/cs2910/prime/docker/startup.py 2

  prime3:
    image: replica-img
    container_name: prime3
    networks:
      prime-net:
        ipv4_address: 172.20.0.4
    command: python3 /root/cs2910/prime/docker/startup.py 3

  prime4:
    image: replica-img
    container_name: prime4
    networks:
      prime-net:
        ipv4_address: 172.20.0.5
    command: python3 /root/cs2910/prime/docker/startup.py 4

  prime5:
    image: replica-img
    container_name: prime5
    networks:
      prime-net:
        ipv4_address: 172.20.0.6
    command: python3 /root/cs2910/prime/docker/startup.py 5

  prime6:
    image: replica-img
    container_name: prime6
    networks:
      prime-net:
        ipv4_address: 172.20.0.7
    command: python3 /root/cs2910/prime/docker/startup.py 6